<a href="https://colab.research.google.com/github/samiul-hasan21/Google-collab-numpy-practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

In [25]:
arr1=np.array([1,2,3,4,5])
print("1D Array:\n",arr1)

1D Array:
 [1 2 3 4 5]


In [26]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [27]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr3)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Arrays Using Different Techniques:

In [28]:
zeros_arr = np.zeros((3,3))
ones_arr = np.ones((2,4))
range_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)
random_arr = np.random.rand(3,3)
identity_arr = np.eye(4)

Some Array Properties:

In [29]:
print("Shape:", arr2.shape)
print("Dimension (ndim):", arr2.ndim)
print("Data type:", arr2.dtype)
print("Size (total elements):", arr2.size)
print("Item size (bytes):", arr2.itemsize)

Shape: (2, 3)
Dimension (ndim): 2
Data type: int64
Size (total elements): 6
Item size (bytes): 8


Some Array Operations

In [30]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


Some Matrix Operations

In [31]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:\n", np.dot(mat1, mat2))
print("Transpose:\n", mat1.T)

Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]


Indexing & Slicing 1D:

In [32]:
arr = np.array([10, 20, 30, 40, 50])
print("First element:", arr[0])
print("Slice (2nd to 4th):", arr[1:4])
print("Step slicing:", arr[::2])

First element: 10
Slice (2nd to 4th): [20 30 40]
Step slicing: [10 30 50]


for 2D:

In [33]:
print("Element at (1,2):", arr2[1,2])
print("Row 0:", arr2[0,:])
print("Column 1:", arr2[:,1])

Element at (1,2): 6
Row 0: [1 2 3]
Column 1: [2 5]


Functions in NumPy

In [34]:
arr = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Square Root:", np.sqrt(arr))


Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Min: 1
Max: 5
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
